@echo off
setlocal EnableExtensions DisableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
set "ENV_FILE=%SCRIPT_DIR%.env"
set "TMP_ENV_FILE=%SCRIPT_DIR%.env.tmp"
if exist "%TMP_ENV_FILE%" del /q "%TMP_ENV_FILE%" >nul 2>nul
set "ENV_MODE=create"
if exist "%ENV_FILE%" set "ENV_MODE=update"

echo.
echo Minecraft Discord Bot .env Setup
echo This tool creates or updates .env without using an editor.
echo Target: %ENV_FILE%
echo Mode: %ENV_MODE%
echo.

echo [1/5] Discord settings
echo DISCORD_TOKEN: Bot token from Discord Developer Portal. Required.
call :prompt_required DISCORD_TOKEN "DISCORD_TOKEN"
echo DISCORD_CHANNEL_ID: Channel ID where the control panel message is posted. Required.
call :prompt_int_required_positive DISCORD_CHANNEL_ID "DISCORD_CHANNEL_ID"
echo BOT_LOG_CHANNEL_ID: Channel ID for bot logs. Set 0 to disable.
call :prompt_int_default BOT_LOG_CHANNEL_ID "BOT_LOG_CHANNEL_ID" "0"
echo.

echo [2/5] Server control settings
echo RCON_HOST: Minecraft server host for RCON.
call :prompt_default RCON_HOST "RCON_HOST" "localhost"
echo RCON_PORT: Minecraft server RCON port.
call :prompt_int_default RCON_PORT "RCON_PORT" "25575"
echo RCON_PASSWORD: Password set in server.properties.
call :prompt_default RCON_PASSWORD "RCON_PASSWORD" "yourpassword"
echo RESTART_COMMAND: Server start .bat path.
echo Use full path or relative path from server root.
call :prompt_default RESTART_COMMAND "RESTART_COMMAND" "run.bat"
echo.

echo [3/5] Minecraft display settings
echo MINECRAFT_PORT: Server game port shown in status.
call :prompt_int_default MINECRAFT_PORT "MINECRAFT_PORT" "25565"
echo MINECRAFT_TYPE: Example Forge / Fabric / Vanilla.
call :prompt_default MINECRAFT_TYPE "MINECRAFT_TYPE" "Forge"
echo MINECRAFT_VER: Example 1.20.1.
call :prompt_default MINECRAFT_VER "MINECRAFT_VER" "1.20.1"
echo MINECRAFT_IP: Address shown in control panel.
call :prompt_default MINECRAFT_IP "MINECRAFT_IP" "localhost"
echo.

echo [4/5] /mods command settings
echo Select how /mods works:
echo   1. disabled: /mods command is disabled.
echo   2. direct: send zip file from bots folder.
echo   3. url: send a download URL.
choice /c 123 /n /m "Select 1-3: "
if errorlevel 3 goto mods_url
if errorlevel 2 goto mods_direct
set "MODS_COMMAND=false"
set "CLIENT_MODS_DIRECTORY="
set "MODS_URL="
goto mods_done

:mods_direct
set "MODS_COMMAND=direct"
echo CLIENT_MODS_DIRECTORY: zip name or path for /mods direct mode.
echo Example: client_mods or client_mods.zip
echo File location: bots\client_mods.zip
call :prompt_default CLIENT_MODS_DIRECTORY "CLIENT_MODS_DIRECTORY" "client_mods"
set "MODS_URL="
goto mods_done

:mods_url
set "MODS_COMMAND=url"
set "CLIENT_MODS_DIRECTORY="
echo MODS_URL: URL that will be sent by /mods.
call :prompt_required MODS_URL "MODS_URL"

:mods_done
echo.
echo [5/5] BlueMap setting
echo BlueMap button is shown only when BLUEMAP_URL is set.
choice /c YN /n /m "Enable BlueMap? [Y/N]: "
if errorlevel 2 (
    set "BLUEMAP_URL="
) else (
    call :prompt_required BLUEMAP_URL "BLUEMAP_URL ^(example: http://sample.f5.si:8100^)"
)

> "%TMP_ENV_FILE%" (
    echo # Generated by setup_env.bat
    echo # Run setup_env.bat again to update values
)
call :write_kv DISCORD_TOKEN "%DISCORD_TOKEN%"
call :write_kv DISCORD_CHANNEL_ID "%DISCORD_CHANNEL_ID%"
call :write_kv BOT_LOG_CHANNEL_ID "%BOT_LOG_CHANNEL_ID%"
call :write_kv MODS_COMMAND "%MODS_COMMAND%"
call :write_kv CLIENT_MODS_DIRECTORY "%CLIENT_MODS_DIRECTORY%"
call :write_kv MODS_URL "%MODS_URL%"
call :write_kv RCON_HOST "%RCON_HOST%"
call :write_kv RCON_PORT "%RCON_PORT%"
call :write_kv RCON_PASSWORD "%RCON_PASSWORD%"
call :write_kv RESTART_COMMAND "%RESTART_COMMAND%"
call :write_kv BLUEMAP_URL "%BLUEMAP_URL%"
call :write_kv MINECRAFT_PORT "%MINECRAFT_PORT%"
call :write_kv MINECRAFT_TYPE "%MINECRAFT_TYPE%"
call :write_kv MINECRAFT_VER "%MINECRAFT_VER%"
call :write_kv MINECRAFT_IP "%MINECRAFT_IP%"

move /Y "%TMP_ENV_FILE%" "%ENV_FILE%" >nul
if errorlevel 1 (
    echo [ERROR] Failed to write .env
    pause
    exit /b 1
)

echo.
if /I "%ENV_MODE%"=="create" (
    echo Created: %ENV_FILE%
) else (
    echo Updated: %ENV_FILE%
)
echo.
pause
exit /b 0

:prompt_required
set "%~1="
:prompt_required_retry
set /p "%~1=%~2: "
if not defined %~1 (
    echo [ERROR] This value is required.
    goto prompt_required_retry
)
exit /b 0

:prompt_default
set /p "%~1=%~2 [%~3]: "
if not defined %~1 set "%~1=%~3"
exit /b 0

:prompt_int_default
set "%~1="
:prompt_int_default_retry
set /p "%~1=%~2 [%~3]: "
if not defined %~1 set "%~1=%~3"
set "NON_NUM="
call set "TMP_VALUE=%%%~1%%"
for /f "delims=0123456789" %%A in ("%TMP_VALUE%") do set "NON_NUM=%%A"
if defined NON_NUM (
    echo [ERROR] Digits only.
    goto prompt_int_default_retry
)
exit /b 0

:prompt_int_required_positive
set "%~1="
:prompt_int_required_positive_retry
set /p "%~1=%~2: "
if not defined %~1 (
    echo [ERROR] This value is required.
    goto prompt_int_required_positive_retry
)
set "NON_NUM="
call set "TMP_VALUE=%%%~1%%"
for /f "delims=0123456789" %%A in ("%TMP_VALUE%") do set "NON_NUM=%%A"
if defined NON_NUM (
    echo [ERROR] Digits only.
    goto prompt_int_required_positive_retry
)
if "%TMP_VALUE%"=="0" (
    echo [ERROR] Value must be greater than 0.
    goto prompt_int_required_positive_retry
)
exit /b 0

:write_kv
>> "%TMP_ENV_FILE%" echo %~1=%~2
exit /b 0
